CREATE DATABASE IF NOT EXISTS foodlog CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE foodlog;

CREATE TABLE IF NOT EXISTS entrees_journal (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL DEFAULT 1,
  date DATE NOT NULL,
  time TIME DEFAULT NULL,
  meal_type VARCHAR(50) NOT NULL,
  food VARCHAR(255) NOT NULL,
  quantity VARCHAR(100) NOT NULL,
  calories INT NOT NULL DEFAULT 0,
  proteins DECIMAL(6,2) NOT NULL DEFAULT 0,
  carbs DECIMAL(6,2) NOT NULL DEFAULT 0,
  fats DECIMAL(6,2) NOT NULL DEFAULT 0,
  note TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS suivi_sante (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL DEFAULT 1,
  date DATE NOT NULL,
  type_activite VARCHAR(100) NOT NULL,
  duree INT NOT NULL COMMENT 'Durée en minutes',
  calories_brulees DECIMAL(8,2) NOT NULL DEFAULT 0,
  intensite VARCHAR(20) NOT NULL DEFAULT 'moyen' COMMENT 'faible, moyen, élevé',
  quantite_eau DECIMAL(8,2) NOT NULL DEFAULT 0 COMMENT 'En mL',
  note TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_user_date_activity (user_id, date, type_activite),
  INDEX idx_user_date (user_id, date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
