CREATE DATABASE IF NOT EXISTS foodlog CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE foodlog;

CREATE TABLE IF NOT EXISTS entrees_journal (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL DEFAULT 1,
  date DATE NOT NULL,
  time TIME DEFAULT NULL,
  meal_type VARCHAR(50) NOT NULL,
  food VARCHAR(255) NOT NULL,
  quantity VARCHAR(100) NOT NULL,
  calories INT NOT NULL DEFAULT 0,
  proteins DECIMAL(6,2) NOT NULL DEFAULT 0,
  carbs DECIMAL(6,2) NOT NULL DEFAULT 0,
  fats DECIMAL(6,2) NOT NULL DEFAULT 0,
  note TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
