CREATE TABLE IF NOT EXISTS utilisateurs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(255) NOT NULL,
  prenom VARCHAR(255) NOT NULL DEFAULT '',
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  photo_profil VARCHAR(500) DEFAULT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  reset_code VARCHAR(10) DEFAULT NULL,
  reset_code_expires_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS profils_nutritionnels (
  id INT AUTO_INCREMENT PRIMARY KEY,
  utilisateur_id INT NOT NULL UNIQUE,
  poids_kg DECIMAL(6,2) NOT NULL,
  taille_cm INT NOT NULL,
  objectif VARCHAR(100) NOT NULL,
  allergies VARCHAR(1024) NOT NULL DEFAULT '',
  regimes VARCHAR(1024) NOT NULL DEFAULT '',
  intolerances VARCHAR(1024) NOT NULL DEFAULT '',
  score_completion INT NOT NULL DEFAULT 0,
  show_weight BOOLEAN DEFAULT 0,
  show_height BOOLEAN DEFAULT 0,
  show_diet BOOLEAN DEFAULT 1,
  show_allergies BOOLEAN DEFAULT 1,
  show_goal BOOLEAN DEFAULT 1,
  show_intolerances BOOLEAN DEFAULT 1,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
